-- MySQL Script generated by MySQL Workbench
-- Wed Oct 10 20:43:13 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pi
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pi` DEFAULT CHARACTER SET utf8 ;
USE `pi` ;

-- -----------------------------------------------------
-- Table `pi`.`cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pi`.`cargo` (
  `id_cargo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `nivel_perfil` VARCHAR(45) NOT NULL,
  `max_desconto` INT NOT NULL,
  PRIMARY KEY (`id_cargo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pi`.`cep`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pi`.`cep` (
  `id_cep` INT NOT NULL,
  `cep` VARCHAR(8) NOT NULL,
  `tipo_logradouro` VARCHAR(15) NOT NULL,
  `logradouro` VARCHAR(100) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `municipio` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`id_cep`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pi`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pi`.`funcionario` (
  `id_funcionario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `login` VARCHAR(30) NOT NULL,
  `senha` VARCHAR(30) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `tel1` VARCHAR(13) NOT NULL,
  `tel2` VARCHAR(13) NULL,
  `complemento` VARCHAR(45) NOT NULL,
  `foto` VARCHAR(200) NOT NULL,
  `salario` DECIMAL(10,2) NOT NULL,
  `fk_id_cargo` INT NOT NULL,
  `fk_id_cep` INT NOT NULL,
  PRIMARY KEY (`id_funcionario`),
  INDEX `fk_id_cargo1_idx` (`fk_id_cargo` ASC),
  INDEX `fk_id_cep2_idx` (`fk_id_cep` ASC),
  CONSTRAINT `fk_id_cargo1`
    FOREIGN KEY (`fk_id_cargo`)
    REFERENCES `pi`.`cargo` (`id_cargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_cep2`
    FOREIGN KEY (`fk_id_cep`)
    REFERENCES `pi`.`cep` (`id_cep`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pi`.`marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pi`.`marca` (
  `id_marca` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `imagem` VARCHAR(200) NULL,
  PRIMARY KEY (`id_marca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pi`.`medida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pi`.`medida` (
  `id_medida` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `unidade` VARCHAR(4) NOT NULL,
  PRIMARY KEY (`id_medida`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pi`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pi`.`produto` (
  `id_produto` INT NOT NULL AUTO_INCREMENT,
  `desc_produto` VARCHAR(45) NOT NULL,
  `qtd_estoque` INT NOT NULL,
  `codigo` VARCHAR(45) NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `imagem` VARCHAR(200) NULL,
  `fk_id_marca` INT NOT NULL,
  `fk_id_medida` INT NOT NULL,
  PRIMARY KEY (`id_produto`),
  INDEX `fk_id_marca_idx` (`fk_id_marca` ASC),
  INDEX `fk_id_medida1_idx` (`fk_id_medida` ASC),
  CONSTRAINT `fk_id_marca`
    FOREIGN KEY (`fk_id_marca`)
    REFERENCES `pi`.`marca` (`id_marca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_medida1`
    FOREIGN KEY (`fk_id_medida`)
    REFERENCES `pi`.`medida` (`id_medida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pi`.`forma_pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pi`.`forma_pagamento` (
  `id_forma_pagamento` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_forma_pagamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pi`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pi`.`cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(11) NULL,
  `cnpj` VARCHAR(14) NULL,
  `tel1` VARCHAR(13) NOT NULL,
  `tel2` VARCHAR(13) NULL,
  `email` VARCHAR(100) NOT NULL,
  `limite_credito` DECIMAL(10,2) NOT NULL,
  `complemento_endereco` VARCHAR(45) NULL,
  `fk_id_cep` INT NOT NULL,
  PRIMARY KEY (`id_cliente`),
  INDEX `fk_id_cep1_idx` (`fk_id_cep` ASC),
  CONSTRAINT `fk_id_cep1`
    FOREIGN KEY (`fk_id_cep`)
    REFERENCES `pi`.`cep` (`id_cep`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pi`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pi`.`venda` (
  `id_venda` INT NOT NULL AUTO_INCREMENT,
  `fk_id_funcionario` INT NOT NULL,
  `fk_id_produto` INT NOT NULL,
  `fk_id_forma_pagamento` INT NOT NULL,
  `fk_id_cliente` INT NOT NULL,
  `numero_parcelas` INT NULL,
  PRIMARY KEY (`id_venda`),
  INDEX `fk_id_funcionario1_idx` (`fk_id_funcionario` ASC),
  INDEX `fk_id_produto1_idx` (`fk_id_produto` ASC),
  INDEX `fk_id_forma_pagamento1_idx` (`fk_id_forma_pagamento` ASC),
  INDEX `fk_id_cliente1_idx` (`fk_id_cliente` ASC),
  CONSTRAINT `fk_id_funcionario1`
    FOREIGN KEY (`fk_id_funcionario`)
    REFERENCES `pi`.`funcionario` (`id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_produto1`
    FOREIGN KEY (`fk_id_produto`)
    REFERENCES `pi`.`produto` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_forma_pagamento1`
    FOREIGN KEY (`fk_id_forma_pagamento`)
    REFERENCES `pi`.`forma_pagamento` (`id_forma_pagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_cliente1`
    FOREIGN KEY (`fk_id_cliente`)
    REFERENCES `pi`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pi`.`itens_venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pi`.`itens_venda` (
  `id_itens_venda` INT NOT NULL AUTO_INCREMENT,
  `qtd` DECIMAL(10,2) NOT NULL,
  `valor_unit` DECIMAL(10,2) NOT NULL,
  `fk_id_produto` INT NOT NULL,
  `fk_id_venda` INT NOT NULL,
  PRIMARY KEY (`id_itens_venda`),
  INDEX `fk_id_produto2_idx` (`fk_id_produto` ASC),
  INDEX `fk_id_venda1_idx` (`fk_id_venda` ASC),
  CONSTRAINT `fk_id_produto2`
    FOREIGN KEY (`fk_id_produto`)
    REFERENCES `pi`.`produto` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_venda1`
    FOREIGN KEY (`fk_id_venda`)
    REFERENCES `pi`.`venda` (`id_venda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
